# Generated by Django 6.0.2 on 2026-02-10 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion_breve', models.TextField()),
                ('descripcion_larga', models.TextField()),
                ('link', models.URLField()),
                ('organizador', models.CharField(max_length=255)),
                ('costo', models.IntegerField()),
                ('duracion', models.CharField(max_length=100)),
                ('edad_min', models.IntegerField()),
                ('edad_max', models.IntegerField()),
                ('lugar', models.CharField(max_length=255)),
                ('inicio_postulacion', models.DateField()),
                ('cierre_postulacion', models.DateField()),
                ('inicio_actividad', models.DateField()),
                ('termino_actividad', models.DateField()),
                ('area', models.ManyToManyField(to='buscador.area')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscador.modalidad')),
                ('pais', models.ManyToManyField(to='buscador.pais')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscador.tipo')),
            ],
        ),
    ]
