# Generated by Django 6.0.2 on 2026-02-10 19:19

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('P', 'Presencial'), ('O', 'Online'), ('H', 'Híbrido')], max_length=3),
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='pais',
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(blank=True, choices=[('TV', 'Taller de verano'), ('TI', 'Taller de invierno'), ('O', 'Olimpiada'), ('CON', 'Concurso'), ('COM', 'Competencia'), ('CU', 'Curso')], max_length=3),
        ),
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': "Área'", 'verbose_name_plural': 'Áreas'},
        ),
        migrations.AddField(
            model_name='actividad',
            name='genero',
            field=models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino'), ('T', 'Todos')], max_length=3),
        ),
        migrations.AddField(
            model_name='actividad',
            name='grado_max',
            field=models.CharField(blank=True, choices=[('PK', 'Pre Kinder'), ('K', 'Kinder'), ('1B', '1° Básico'), ('2B', '2° Básico'), ('3B', '3° Básico'), ('4B', '4° Básico'), ('5B', '5° Básico'), ('6B', '6° Básico'), ('7B', '7° Básico'), ('8B', '8° Básico'), ('1M', '1° Medio'), ('2M', '2° Medio'), ('3M', '3° Medio'), ('4M', '4° Medio'), ('Uni', 'Universitario')], max_length=3),
        ),
        migrations.AddField(
            model_name='actividad',
            name='grado_min',
            field=models.CharField(blank=True, choices=[('PK', 'Pre Kinder'), ('K', 'Kinder'), ('1B', '1° Básico'), ('2B', '2° Básico'), ('3B', '3° Básico'), ('4B', '4° Básico'), ('5B', '5° Básico'), ('6B', '6° Básico'), ('7B', '7° Básico'), ('8B', '8° Básico'), ('1M', '1° Medio'), ('2M', '2° Medio'), ('3M', '3° Medio'), ('4M', '4° Medio'), ('Uni', 'Universitario')], max_length=3),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='cierre_postulacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='costo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='duracion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='edad_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='edad_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='inicio_actividad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='inicio_postulacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='lugar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='organizador',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='termino_actividad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Modalidad',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.AddField(
            model_name='actividad',
            name='pais',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True),
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
