# Generated by Django 6.0.2 on 2026-02-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0002_alter_actividad_modalidad_remove_actividad_pais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='info_extra',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='requisitos',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('TV', 'Taller de verano'), ('TI', 'Taller de invierno'), ('O', 'Olimpiada'), ('CON', 'Concurso'), ('COM', 'Competencia'), ('CU', 'Curso')], max_length=3),
        ),
    ]
