# Generated by Django 6.0.2 on 2026-02-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0003_actividad_info_extra_actividad_requisitos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='requisitos',
            new_name='otros_requisitos',
        ),
    ]
